import assert from "node:assert/strict"
import { readFile } from "node:fs/promises"

const root = new URL("../", import.meta.url)
const read = (path) => readFile(new URL(path, root), "utf8")

const page = await read("app/page.tsx")
const start = await read("app/components/TerraStartScreen.tsx")
const startStyles = await read("app/components/TerraStartScreen.module.css")
const movableTitle = await read("app/components/MovableStartTitle.tsx")
const authPanel = await read("app/components/TerraAuthPanel.tsx")
const authStyles = await read("app/components/TerraAuthPanel.module.css")
const characters = await read("app/game/characters.ts")
const commandCenter = await read("app/components/TerraCommandCenter.tsx")
const commandStyles = await read("app/components/TerraCommandCenter.module.css")

for (const screen of ["START", "CHARACTER_CREATE", "COMMAND", "HOME", "LOADING", "PLAZA"]) {
  assert.match(`${page}\n${await read("app/game/types.ts")}`, new RegExp(`\"${screen}\"`))
}

for (const layer of ["space-base.png", "terra.png", "luna.png", "sol.png", "star-twinkle", "star-glint", "sun-corona"]) {
  assert.ok(startStyles.includes(layer), `missing start layer: ${layer}`)
}
assert.match(start, /starField/)
assert.match(start, /sunCorona/)
assert.match(movableTitle, /titleWordmark/)
assert.match(movableTitle, /테라 접속/)
assert.doesNotMatch(start, /createAccountButton/)
assert.match(start, /cometTrack/)
assert.match(start, /effectStarsFar/)
assert.match(start, /<MovableStartTitle onConnect=\{onLogin\}/)
assert.doesNotMatch(start, /setAuthMode/)
assert.match(start, /cometSix/)
assert.match(movableTitle, /terra-start-title-position/)
assert.match(movableTitle, /titleReady/)
assert.match(startStyles, /\.titleOnly \{.*opacity:0/)
assert.doesNotMatch(movableTitle, /위치 조정/)
assert.doesNotMatch(movableTitle, /위치 고정/)
assert.doesNotMatch(movableTitle, /setPointerCapture/)
assert.match(start, /effectStarsDense/)
assert.doesNotMatch(start, /<TerraAuthPanel/)
assert.doesNotMatch(start, /orbitLayer/)
assert.doesNotMatch(startStyles, /orbit-drift/)
assert.match(startStyles, /prefers-reduced-motion/)

for (const label of ["게임 소개", "익명성이 말을 거칠게", "경계 때문에 먼저 다가가기 어렵습니다", "부담 없이 만나고 협력", "광장을 탐사하고 자원 수집", "다시 만나 반가워요", "첫 탐사를 준비하세요", "아이디 또는 이메일", "비밀번호 확인", "챗지피티로 계속하기"]) assert.ok(authPanel.includes(label), `missing auth panel label: ${label}`)
for (const label of ["RETURNING EXPLORER", "NEW EXPLORER", "FIRST CONTACT", "관제망에 접속"]) assert.ok(!authPanel.includes(label), `auth panel still contains mixed-language label: ${label}`)
assert.match(authPanel, /role="dialog"/)
assert.match(authPanel, /current-password/)
assert.match(authPanel, /NEXT_PUBLIC_CHATGPT_AUTH_ENABLED/)
assert.match(authPanel, /입력값과 비밀번호를 저장하지 않습니다/)
assert.doesNotMatch(authPanel, /localStorage/)
assert.match(authStyles, /backdrop-filter/)
assert.match(authStyles, /prefers-reduced-motion/)
assert.match(startStyles, /comet-flight 30s linear infinite/)
assert.match(startStyles, /animation-delay:-5s/)
assert.match(startStyles, /translate3d\(154vw,0,0\)/)
assert.match(startStyles, /\.cometTrack \{ display:none; \}/)

assert.match(page, /PROFILE_STORAGE_KEY/)
assert.match(page, /LOADING_DURATION_MS/)
assert.match(page, /localStorage/)
assert.match(page, /LoadingSpinner/)
assert.match(page, /configure-border-1/)
assert.match(page, /configure-border-2/)
assert.match(page, /TERRA에 진입하는 중/)
assert.match(page, /storedProfile \? "COMMAND" : "CHARACTER_CREATE"/)
assert.match(page, /setScreen\("COMMAND"\)/)
assert.match(page, /<TerraCommandCenter/)
assert.match(page, /onEnterTerra=\{\(\) => beginLoading\("plaza"\)\}/)
assert.match(page, /initialProfile=\{profile\}/)
assert.match(page, /PROFILE EDITOR/)
assert.doesNotMatch(page, /loading-track/)
assert.doesNotMatch(page, /screen-transition/)
assert.doesNotMatch(page, /<TerminalPanel/)
assert.doesNotMatch(page, /<GlobalChatDock/)

const globalStyles = await read("app/globals.css")
assert.match(globalStyles, /configure-clockwise/)
assert.match(globalStyles, /configure-xclockwise/)
assert.match(globalStyles, /configure-core/)
assert.match(globalStyles, /loading-screen \{ align-items: center; background: #000;/)
assert.match(globalStyles, /play-header/)
assert.match(globalStyles, /play-stage/)

for (const label of ["항로", "광장", "전초기지", "작전", "TERRA 입장하기", "전체 채팅", "신입대원"]) assert.ok(commandCenter.includes(label), `missing command center label: ${label}`)
assert.doesNotMatch(commandCenter, /id: "chat"|교신망|OPEN CHANNEL/)
for (const chatLabel of ["전체", "지역", "시스템", "12명 접속"]) assert.ok(commandCenter.includes(chatLabel), `missing game chat detail: ${chatLabel}`)
assert.doesNotMatch(commandCenter, /Enter 전송|도움말/)
for (const material of ["목재", "철", "시그널 잔해", "재활용 부품"]) assert.ok(commandCenter.includes(material), `missing shared material: ${material}`)
assert.match(commandCenter, /useState<PlanetId \| null>\(null\)/)
assert.match(commandCenter, /selectedPlanet && planet/)
assert.match(commandCenter, /setSelectedPlanet\(null\)/)
assert.doesNotMatch(commandCenter, /code: "ROUTE"/)
assert.match(commandCenter, /<RouteMap progress=\{progress\}/)
assert.match(commandCenter, /<PlazaView nickname=\{profile.nickname\}/)
for (const plazaLabel of ["광장 뉴스", "교정시설 관찰실", "미니게임", "광장 낚시", "3분 축구", "광장 소식과 채팅"]) assert.ok(commandCenter.includes(plazaLabel), `missing plaza layout label: ${plazaLabel}`)
assert.doesNotMatch(commandCenter, /현실 미션 기록|missionSpotlight|missionRecords|모집 메시지 보내기/)
assert.match(commandCenter, /function ChatDrawer/)
assert.match(commandCenter, /aria-expanded=\{open\}/)
assert.match(commandCenter, /chatDrawerToggle/)
for (const layer of ["space-base.png", "terra.png", "luna.png", "sol.png"]) assert.ok(commandStyles.includes(layer), `missing route layer: ${layer}`)
assert.doesNotMatch(commandStyles, /terra-route-map\.png/)
assert.match(commandStyles, /background-size:cover/)
assert.match(commandStyles, /\.routeChat/)
assert.match(commandStyles, /\.chatChannels/)
assert.match(commandStyles, /\.systemMessage/)
assert.match(commandStyles, /\.chatDrawerClosed/)
for (const plazaClass of ["plazaGrid", "plazaRightColumn", "plazaInfoRow", "plazaCctv", "plazaMiniGames"]) assert.match(commandStyles, new RegExp(`\\.${plazaClass}`))
assert.match(commandStyles, /\.plazaGrid \{[^}]*grid-template-columns:minmax\(0,1fr\) minmax\(0,1fr\)[^}]*grid-template-rows:minmax\(0,1fr\)/)
assert.match(commandStyles, /\.plazaRightColumn \{[^}]*grid-template-rows:minmax\(0,1\.35fr\) minmax\(220px,\.65fr\)/)
assert.match(commandStyles, /\.plazaInfoRow \{[^}]*grid-template-columns:minmax\(0,\.82fr\) minmax\(0,1\.18fr\)/)
assert.match(commandStyles, /scrollbar-color/)
assert.match(commandStyles, /::-webkit-scrollbar-thumb/)
assert.match(commandStyles, /\.planetTerra \{ bottom:38%; left:36%; min-width:150px/)
assert.match(commandStyles, /\.planetLuna \{ left:52%; top:19%;/)
assert.match(commandStyles, /\.planetSol \{ right:12%; top:18%;/)
assert.match(commandStyles, /\.planetLuna .*transform:translate\(-30px,-20px\)/)
assert.match(commandStyles, /\.planetSol .*transform:translateX\(30px\)/)
assert.match(commandStyles, /\.routeChat .*height:360px/)
assert.match(commandStyles, /\.routeChat header \{ padding:9px 18px; \}/)
assert.match(commandStyles, /\.routeSol .*transform:translate3d\(-7%,7%,0\)/)
assert.match(commandStyles, /font-size:16px/)
assert.match(commandStyles, /chatMessages p/)
assert.match(commandStyles, /prefers-reduced-motion/)
const commandUi = await read("app/components/TerraCommandUi.tsx")
for (const resource of ["wood", "iron", "signal", "reclaimed"]) assert.ok(commandUi.includes(`${resource}: <>`), `missing SVG resource icon: ${resource}`)
assert.match(commandUi, /viewBox="0 0 24 24"/)

assert.match(characters, /terra-explorer-v3\/direction-atlas/)
assert.match(characters, /terra-explorer-v4\/female-cute/)
assert.match(characters, /getCharacterWalkSheetPath/)
assert.match(characters, /getCharacterInteractionSheetPath/)
assert.match(characters, /CHARACTER_DIRECTION_ATLASES/)
assert.match(characters, /DIRECTION_ATLAS_CELLS/)
assert.match(characters, /CHARACTER_FRAME_SIZE = 256/)
assert.match(characters, /DIRECTION_ATLAS_SIZE/)
for (const direction of ["down", "down-left", "left", "up-left", "up", "up-right", "right", "down-right"]) assert.ok(characters.includes(direction), `missing ${direction} sprite direction`)
assert.doesNotMatch(page, /PAPER_DOLL_PREVIEW_LAYERS/)
assert.doesNotMatch(page, /paper-preview-layer/)
for (const variant of ["CHARACTER_PRESETS", "HEAD_LABELS", "headVariant"]) assert.match(page, new RegExp(variant), `missing fixed character style field: ${variant}`)
for (const preset of ["male-cute", "male-composed", "female-cute", "female-composed"]) assert.ok(page.includes(preset), `missing character preset: ${preset}`)
assert.match(page, /character-preset-grid/)
assert.doesNotMatch(page, /HAIR_VARIANTS/)
assert.doesNotMatch(page, /OUTFIT_VARIANTS/)
const world = await read("app/game/world.ts")
assert.match(world, /export function movePoint/)
assert.match(world, /export function findNearestResource/)
assert.match(world, /signal-fragment-east/)
const canvas = await read("app/components/TerraCanvas.tsx")
assert.ok(page.includes("F 상호작용"))
for (const layer of ["drawGround(context, scene)", "drawPath(context, scene)", "drawStructure(context", "drawProps(context, scene)", "drawForeground(context)"]) assert.ok(canvas.includes(layer), `missing renderer layer: ${layer}`)
assert.ok(canvas.includes("getDirectionAtlasCell"))
assert.ok(canvas.includes("getCharacterAtlasPath"))
assert.ok(canvas.includes("getCharacterWalkSheetPath"))
assert.ok(canvas.includes("getCharacterInteractionSheetPath"))
assert.ok(canvas.includes("interaction-hand"))
assert.ok(canvas.includes("setInteracting"))
assert.ok(canvas.includes('key === "f"'))
assert.ok(canvas.includes("interactionFrame"))
assert.doesNotMatch(canvas, /onOpenTerminal/)
assert.doesNotMatch(canvas, /community-terminal/)
assert.match(canvas, /data-sprite-direction/)
assert.match(canvas, /data-sprite-frame/)
assert.match(canvas, /requestAnimationFrame\(tick\)/)
assert.match(canvas, /prefers-reduced-motion/)

console.log("TERRA source checks passed")
