import assert from "node:assert/strict"
import { readFile } from "node:fs/promises"

const root = new URL("../", import.meta.url)
const read = (path) => readFile(new URL(path, root), "utf8")

const page = await read("app/page.tsx")
const start = await read("app/components/TerraStartScreen.tsx")
const startStyles = await read("app/components/TerraStartScreen.module.css")
const movableTitle = await read("app/components/MovableStartTitle.tsx")
const authPanel = await read("app/components/TerraAuthPanel.tsx")
const authStyles = await read("app/components/TerraAuthPanel.module.css")
const characters = await read("app/game/characters.ts")
const commandCenter = await read("app/components/TerraCommandCenter.tsx")
const commandStyles = await read("app/components/TerraCommandCenter.module.css")

for (const screen of ["START", "CHARACTER_CREATE", "COMMAND", "HOME", "LOADING", "PLAZA", "FOREST"]) {
  assert.match(`${page}\n${await read("app/game/types.ts")}`, new RegExp(`\"${screen}\"`))
}

for (const layer of ["space-base.png", "terra.png", "luna.png", "sol.png", "star-twinkle", "star-glint", "sun-corona"]) {
  assert.ok(startStyles.includes(layer), `missing start layer: ${layer}`)
}
assert.match(start, /starField/)
assert.match(start, /sunCorona/)
assert.match(movableTitle, /titleWordmark/)
assert.doesNotMatch(start, /createAccountButton/)
assert.match(start, /cometTrack/)
assert.match(start, /effectStarsFar/)
assert.match(start, /<MovableStartTitle onConnect=\{onLogin\}/)
assert.doesNotMatch(start, /setAuthMode/)
assert.match(start, /cometSix/)
assert.match(movableTitle, /terra-start-title-position/)
assert.match(movableTitle, /titleReady/)
assert.match(startStyles, /\.titleOnly \{.*opacity:0/)
assert.doesNotMatch(movableTitle, /setPointerCapture/)
assert.match(start, /effectStarsDense/)
assert.doesNotMatch(start, /<TerraAuthPanel/)
assert.doesNotMatch(start, /orbitLayer/)
assert.doesNotMatch(startStyles, /orbit-drift/)
assert.match(startStyles, /prefers-reduced-motion/)

assert.match(authPanel, /auth-title/)
assert.match(authPanel, /auth-title/)
assert.match(authPanel, /role="dialog"/)
assert.match(authPanel, /current-password/)
assert.match(authPanel, /NEXT_PUBLIC_CHATGPT_AUTH_ENABLED/)
assert.match(authPanel, /prototypeNote/)
assert.doesNotMatch(authPanel, /localStorage/)
assert.match(authStyles, /backdrop-filter/)
assert.match(authStyles, /prefers-reduced-motion/)
assert.match(startStyles, /comet-flight 30s linear infinite/)
assert.match(startStyles, /animation-delay:-5s/)
assert.match(startStyles, /translate3d\(2464px,0,0\)/)
assert.match(startStyles, /\.cometTrack \{ display:none; \}/)

assert.match(page, /PROFILE_STORAGE_KEY/)
assert.match(page, /LOADING_DURATION_MS/)
assert.match(page, /localStorage/)
assert.match(page, /LoadingSpinner/)
assert.match(page, /configure-border-1/)
assert.match(page, /configure-border-2/)
assert.match(page, /TERRA/)
assert.match(page, /loadingDestination === "login"/)
assert.match(page, /setProfile\(null\)/)
assert.match(page, /setScreen\("CHARACTER_CREATE"\)/)
assert.match(page, /setScreen\("COMMAND"\)/)
assert.match(page, /<TerraCommandCenter/)
assert.match(page, /onEnterTerra=\{\(\) => beginLoading\("plaza"\)\}/)
assert.match(page, /initialProfile=\{profile\}/)
assert.match(page, /PROFILE EDITOR/)
assert.doesNotMatch(page, /onEditProfile/)
assert.doesNotMatch(page, /loading-track/)
assert.doesNotMatch(page, /screen-transition/)
assert.doesNotMatch(page, /<TerminalPanel/)
assert.doesNotMatch(page, /<GlobalChatDock/)

const globalStyles = await read("app/globals.css")
assert.match(globalStyles, /configure-clockwise/)
assert.match(globalStyles, /configure-xclockwise/)
assert.match(globalStyles, /configure-core/)
assert.match(globalStyles, /configure-border-1, \.configure-border-2 \{[^}]*border-radius: 0/)
assert.match(globalStyles, /configure-core \{[^}]*border-radius: 0/)
assert.match(globalStyles, /loading-screen \{ align-items: center; background: #000;/)
assert.match(globalStyles, /play-header/)
assert.match(globalStyles, /play-stage/)

assert.match(commandCenter, /RouteMap/)
assert.match(commandCenter, /useState<TerminalTab>\("community"\)/)
assert.doesNotMatch(commandCenter, /id: "chat"|OPEN CHANNEL/)
assert.match(commandCenter, /chatChannels/)
assert.match(commandCenter, /useState<PlanetId \| null>\(null\)/)
assert.match(commandCenter, /selectedPlanet && planet/)
assert.match(commandCenter, /setSelectedPlanet\(null\)/)
assert.doesNotMatch(commandCenter, /code: "ROUTE"/)
assert.match(commandCenter, /<RouteMap progress=\{currentProgress\}/)
assert.match(commandCenter, /<PlazaView nickname=\{profile.nickname\}/)
assert.match(commandCenter, /plazaView/)
assert.doesNotMatch(commandCenter, /missionSpotlight|missionRecords/)
assert.match(commandCenter, /function ChatDrawer/)
assert.match(commandCenter, /export function ChatWindow/)
assert.match(commandCenter, /export function PlazaNewsPanel/)
assert.match(commandCenter, /aria-expanded=\{open\}/)
assert.match(commandCenter, /chatDrawerToggle/)
assert.doesNotMatch(commandCenter, /window\.setInterval\(spawnMission, 5000\)/)
assert.doesNotMatch(commandCenter, /expirationTimers/)
assert.match(commandCenter, /onRerollMission=\{rerollMission\}/)
assert.match(commandCenter, /title: "창가의 숨"/)
assert.match(commandCenter, /title: "빛의 흔적 따라가기"/)
for (const layer of ["space-base.png", "terra.png", "luna.png", "sol.png"]) assert.ok(commandStyles.includes(layer), `missing route layer: ${layer}`)
assert.doesNotMatch(commandStyles, /terra-route-map\.png/)
assert.match(commandStyles, /background-size:cover/)
assert.match(commandStyles, /\.routeChat/)
assert.match(commandStyles, /\.chatChannels/)
assert.match(commandStyles, /\.systemMessage/)
assert.match(commandStyles, /\.chatDrawerClosed/)
for (const plazaClass of ["plazaGrid", "plazaRightColumn", "plazaInfoRow", "plazaCctv", "plazaMiniGames"]) assert.match(commandStyles, new RegExp(`\\.${plazaClass}`))
assert.match(commandStyles, /\.plazaGrid \{[^}]*grid-template-columns:minmax\(0,1fr\) minmax\(0,1fr\)[^}]*grid-template-rows:minmax\(0,1fr\)/)
assert.match(commandStyles, /\.plazaRightColumn \{[^}]*grid-template-rows:minmax\(0,1\.35fr\) minmax\(220px,\.65fr\)/)
assert.match(commandStyles, /\.plazaInfoRow \{[^}]*grid-template-columns:minmax\(0,\.82fr\) minmax\(0,1\.18fr\)/)
assert.match(commandStyles, /scrollbar-color/)
assert.match(commandStyles, /::-webkit-scrollbar-thumb/)
assert.match(commandStyles, /\.planetTerra \{ bottom:38%; left:36%; min-width:150px/)
assert.match(commandStyles, /\.planetLuna \{ left:52%; top:19%;/)
assert.match(commandStyles, /\.planetSol \{ right:12%; top:18%;/)
assert.match(commandStyles, /\.planetLuna .*transform:translate\(-50px,-90px\)/)
assert.match(commandStyles, /\.planetSol .*transform:translateX\(30px\)/)
assert.match(commandStyles, /\.routeChat .*height:320px/)
assert.match(commandStyles, /\.routeChat\.chatPanel > header \{ padding:6px 18px; \}/)
assert.match(commandStyles, /\.routeSol .*transform:translate3d\(-7%,7%,0\)/)
assert.match(commandStyles, /\.routeSol .*background-position:center top/)
assert.match(commandStyles, /font-size:16px/)
assert.match(commandStyles, /chatMessages p/)
assert.match(commandStyles, /prefers-reduced-motion/)
assert.doesNotMatch(commandCenter, /onEditProfile/)
const commandUi = await read("app/components/TerraCommandUi.tsx")
for (const resource of ["wood", "iron", "signal", "reclaimed"]) assert.ok(commandUi.includes(`${resource}: <>`), `missing SVG resource icon: ${resource}`)
assert.match(commandUi, /viewBox="0 0 24 24"/)

assert.match(characters, /characterSpriteFolder/)
assert.match(characters, /terra-male|TERRA-feamale/)
assert.match(characters, /walk-4x4/)
assert.match(characters, /idle-4x4/)
assert.match(characters, /run-4x4/)
assert.match(characters, /interaction-4x4/)
assert.match(characters, /silver-braid/)
assert.match(characters, /terra-explorer-v15\/female-silver-braid/)
assert.match(characters, /terra-explorer-v17\/male\/walk-4x4/)
assert.match(characters, /terra-explorer-v17\/female-silver-braid\/walk-4x4/)
assert.match(characters, /walk: \[0, 1, 2, 3\]/)
assert.match(characters, /gender === "male" && \(action === "walk" \|\| action === "run"\)/)
assert.match(characters, /flipX: requestedRow === 2/)
assert.match(characters, /style === "silver-braid" \? characterSheetPath\(gender, style, "walk-4x4"\)/)
assert.doesNotMatch(characters, /8x4|usesEightDirection/)
assert.match(characters, /getCharacterWalkSheetPath/)
assert.match(characters, /getCharacterIdleSheetPath/)
assert.match(characters, /getCharacterInteractionSheetPath/)
assert.match(characters, /getCharacterSheetFrame/)
assert.match(characters, /SILVER_BRAID_SIDE_FRAME_ORDER/)
assert.match(characters, /CHARACTER_DIRECTION_ATLASES/)
assert.match(characters, /DIRECTION_ATLAS_CELLS/)
assert.match(characters, /CHARACTER_FRAME_SIZE = 256/)
assert.match(characters, /DIRECTION_ATLAS_SIZE/)
for (const direction of ["down", "down-left", "left", "up-left", "up", "up-right", "right", "down-right"]) assert.ok(characters.includes(direction), `missing ${direction} sprite direction`)
assert.doesNotMatch(page, /PAPER_DOLL_PREVIEW_LAYERS/)
assert.doesNotMatch(page, /paper-preview-layer/)
assert.doesNotMatch(page, /CHARACTER_PRESETS|HEAD_LABELS|character-preset-grid|body-type-label/)
assert.match(page, /id="gender-label"/)
assert.doesNotMatch(page, /id="character-variant-label"|캐릭터 타입/)
assert.match(page, /CHARACTER_VARIANT_FOR_GENDER = \{ male: "composed", female: "silver-braid" \}/)
assert.match(page, /getCharacterIdleSheetPath\(gender, headVariant\)/)
assert.match(page, /choice === "male" \? copy\.male : copy\.female/)
assert.match(page, /id="outfit-color-label"/)
assert.doesNotMatch(page, /HAIR_VARIANTS/)
assert.doesNotMatch(page, /OUTFIT_VARIANTS/)
const world = await read("app/game/world.ts")
assert.match(world, /export function movePoint/)
assert.match(world, /export function findNearestResource/)
assert.match(world, /signal-fragment-east/)
const canvas = await read("app/components/TerraCanvas.tsx")
assert.ok(page.includes("F "))
for (const layer of ["drawGround(context, scene)", "drawPath(context, scene)", "drawStructure(context", "drawProps(context, scene)", "drawForeground(context)"]) assert.ok(canvas.includes(layer), `missing renderer layer: ${layer}`)
assert.ok(canvas.includes("getDirectionAtlasCell"))
assert.ok(canvas.includes("getCharacterAtlasPath"))
assert.ok(canvas.includes("getCharacterWalkSheetPath"))
assert.ok(canvas.includes("getCharacterIdleSheetPath"))
assert.ok(canvas.includes("getCharacterInteractionSheetPath"))
assert.ok(canvas.includes("getCharacterSheetFrame"))
assert.ok(canvas.includes("interaction-hand"))
assert.ok(canvas.includes("setInteracting"))
assert.ok(canvas.includes('key === "f"'))
assert.ok(canvas.includes("interactionFrame"))
assert.doesNotMatch(canvas, /onOpenTerminal/)
assert.doesNotMatch(canvas, /community-terminal/)
assert.match(canvas, /data-sprite-direction/)
assert.match(canvas, /data-sprite-frame/)
assert.match(canvas, /requestAnimationFrame\(tick\)/)
assert.match(canvas, /prefers-reduced-motion/)

const fixedCanvas = await read("app/components/FixedGameCanvas.tsx")
const fixedCanvasStyles = await read("app/components/FixedGameCanvas.module.css")
const layout = await read("app/layout.tsx")
assert.match(fixedCanvas, /DESIGN_WIDTH = 1600/)
assert.match(fixedCanvas, /DESIGN_HEIGHT = 900/)
assert.match(fixedCanvas, /Math\.min\(window\.innerWidth \/ DESIGN_WIDTH, window\.innerHeight \/ DESIGN_HEIGHT\)/)
assert.match(fixedCanvasStyles, /height: 900px/)
assert.match(fixedCanvasStyles, /width: 1600px/)
assert.match(layout, /<FixedGameCanvas>\{children\}<\/FixedGameCanvas>/)

const forest = await read("app/components/TerraForestPrototype.tsx")
const forestStyles = await read("app/components/TerraForestPrototype.module.css")
const forestScene = await read("app/components/TerraForestScene.tsx")
for (const feature of ["TERRA", "TerraForestScene"]) assert.ok(forest.includes(feature))
for (const feature of ["@react-three/fiber", "orthographic", "camera.position.copy", "camera.getWorldDirection", "cameraRight", "zoom:64", "TerraLevelObjects", "FlowerField", "getCharacterIdleSheetPath", "loadedIdleTexture", "getCharacterWalkSheetPath", "getCharacterRunSheetPath", "getCharacterInteractionSheetPath", "getCharacterSheetFrame", "interactionRef", "TextureLoader", "keyup", "key===\"shift\"", "performance.now()", "interacting"]) assert.ok(forestScene.includes(feature), `missing 3D forest feature: ${feature}`)
assert.match(forestScene, /moving \? "walk" : "idle"/)
assert.match(forestScene, /repeat\.x = sheetFrame\.flipX \? -\.25 : \.25/)
assert.match(forestScene, /sheetFrame\.frame \+ \(sheetFrame\.flipX \? 1 : 0\)/)
assert.doesNotMatch(forestScene, /player\.current\.scale\.x = sheetFrame\.flipX/)
const levelObjects = await read("app/components/TerraLevelObjects.tsx")
const levelEditor = await read("app/tools/level-editor/LevelEditor.tsx")
const editorViewport = await read("app/tools/level-editor/EditorViewport.tsx")
const editorServer = await read("tools/level-editor/server.mjs")
const levelData = await read("app/game/level.ts")
const plazaLevel = await read("app/game/levels/terra-plaza.json")
for (const feature of ["GLTFLoader", "terra-forest.json", "readLevelDocument"]) assert.ok(levelObjects.includes(feature), `missing level runtime feature: ${feature}`)
for (const feature of ["EditorViewport", "JSON.stringify", "exportLevel", "save"]) assert.ok(levelEditor.includes(feature))
for (const feature of ["127.0.0.1", "MAX_ASSET_SIZE", "isLevel", "levelFile"]) assert.ok(editorServer.includes(feature))
for (const feature of ["TerrainMaterial", "LevelWall", "createDefaultLevel", "getTerrainHeight", "getTerrainSurfaceHeight", "isLevelPositionBlocked"]) assert.ok(levelData.includes(feature), `missing terrain data feature: ${feature}`)
for (const feature of ["initialLevels", "EditorViewport", "pieceSize", "placementKind", "terrainTool"]) assert.ok(levelEditor.includes(feature), `missing editor feature: ${feature}`)
for (const feature of ["MOUSE.ROTATE", "MOUSE.PAN", "TerrainSurface", "onPointerMove", "TransformControls", "controls.mouseButtons.LEFT = null", "brushPoint", "addQuad([top[0], top[3], top[2], top[1]])"]) assert.ok(editorViewport.includes(feature), `missing viewport input feature: ${feature}`)
assert.match(levelObjects, /addQuad\(\[top\[0\], top\[3\], top\[2\], top\[1\]\]\)/)
assert.match(editorServer, /\/levels/)
assert.match(editorServer, /queryId\(request\)/)
assert.match(editorServer, /pathname === "\/level"/)
assert.match(plazaLevel, /terra-plaza/)
assert.doesNotMatch(levelObjects, /tree-quaternius/i)
assert.doesNotMatch(forestScene, /tree-quaternius/i)
assert.doesNotMatch(forestScene, /WatercolorTree|TREES/)
assert.match(forestStyles, /viewport canvas/)
assert.match(forestStyles, /@keyframes region-intro/)
assert.match(forestStyles, /forest-enter/)
assert.match(forest, /ResourceHud inventory=\{inventory\}/)
assert.match(forest, /profileLevel/)
assert.match(forest, /returnBar/)
assert.doesNotMatch(forest, /시그널 안정/)
assert.match(forest, /ChatWindow/)
assert.match(forest, /PlazaNewsPanel/)
assert.match(forest, /messages=\{messages\}/)
assert.match(forest, /onSendMessage/)
assert.doesNotMatch(forest, /FOREST_MESSAGE_POOL|FOREST_NEWS|숲 전체 채팅 메시지|실시간 통신망/)
assert.match(forestStyles, /height:76px/)
assert.match(forestStyles, /height:824px/)
assert.match(forestStyles, /background:transparent.*returnBar/)
assert.match(forestStyles, /commsRail/)
assert.match(page, /chatMessages/)
assert.match(page, /onSendMessage=\{sendChatMessage\}/)
assert.match(page, /loading-screen--forest/)
assert.match(page, /바람이 머무는 숲/)
assert.doesNotMatch(forest, /className=\{styles\.controls\}/)
assert.match(page, /setScreen\("FOREST"\)/)

console.log("TERRA source checks passed")

assert.doesNotMatch(levelData, /WaterSettings|WaterPatch/)
assert.doesNotMatch(levelEditor, /waterPlacement|patchWater|placeWater/)
assert.doesNotMatch(levelObjects, /TerraWater|level\.water/)
